# This workflow will publish the Electron application files to GitHub Releases when a new tag is created

name: Client Release CD
on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: client

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    steps:
    - uses: actions/checkout@v2       
    - uses: actions/setup-node@master
      with:
        node-version: 19
        check-latest: true
    - name: Install Dependencies
      run: npm ci
    - name: Publish Electron Application
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run publish