name: Machine Learning Model CI

on:
  schedule:
    - cron: '0 3 * * 6'

permissions:
  contents: read

jobs:
  ml-model:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: machine-learning

    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install Machine Learning Dependencies
        run: pip install -r requirements.txt

      - name: Generate Machine Learning Model
        run: python model.py

      - name: Save Machine Learning Model
        uses: actions/upload-artifact@v3
        with:
          name: ml-model
          path: machine-learning/model.pth
