name: Admin Backend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  ml-model:
    runs-on: ubuntu-latest
    permissions: write-all
    defaults:
      run:
        working-directory: machine-learning

    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install Machine Learning Dependencies
        run: pip install -r requirements.txt

      - name: Generate Machine Learning Model
        run: python model.py
        
      - name: Delete Old Artifacts
        uses: actions/github-script@v6
        id: artifact
        with:
          script: |
            const res = await github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })

            res.data.artifacts
              .forEach(({ id }) => {
                github.rest.actions.deleteArtifact({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  artifact_id: id,
                })
              })

      - name: Save Machine Learning Model
        uses: actions/upload-artifact@v3
        with:
          name: ml-model
          path: machine-learning/model.pth
          
          
  build:
    runs-on: ${{ matrix.os }}
    needs: ml-model
    defaults:
      run:
        working-directory: admin-system/backend

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pipenv'
    
    - name: Install pipenv
      run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python

    - name: Install Backend Dependencies
      run: pipenv sync --dev

    - name: Download Machine Learning Model
      uses: actions/download-artifact@v3
      with:
        name: ml-model
        path: admin-system/backend/instance/

    - name: Test with pytest
      run: pipenv run pytest --cov=api --cov-branch


  build-docker:
    runs-on: ubuntu-latest
    needs: ml-model
    defaults:
      run:
        working-directory: admin-system/backend

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Download Machine Learning Model
      uses: actions/download-artifact@v3
      with:
        name: ml-model
        path: admin-system/backend/instance/
    
    - name: Build and Push
      uses: docker/build-push-action@v4
      with:
        context: ./admin-system/backend
        platforms: linux/amd64
        load: true
        push: false
        tags: admin-system-backend
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Run Tests
      run: docker run --rm admin-system-backend /usr/src/.venv/bin/python -m pytest --cov=api --cov-branch
